# site settings
title: Yeni
subtitle: Yeri
email: yeniyericomgithub@f2r.org
description: Welcome to YeniYeri.<br />The fresh way of gathering content.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Center St
city: Hometown
state: CT
zip_code: 06492
country: United States of America
phone: +1 (260)7-VOLKAN

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/volkanger
googleplus_url: https://plus.google.com/u/0/+volkanger
instagram_url: https://instagram.com/volkanger
linkedin_url: https://www.linkedin.com/in/volkanger
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cibinlik

# build settings
markdown: kramdown

sass:
  style: compressed
