# site settings
title: Yeni
subtitle: Yeri
email: yeniyericomgithub@f2r.org
description: Welcome to my humble site. I hope you'll<br />stay longer than Average Session Duration.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Center St
city: Hometown
state: CT
zip_code: 06492
country: United States of America
phone: +1 (260)7-VOLKAN

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
